#!/usr/bin/env python3
"""
Fetch real historical stock prices from yfinance for all game rounds.
Outputs frontend/src/data/stockPrices.js with daily closing prices.
"""

import json
import os
from datetime import datetime

import yfinance as yf

ROUNDS = [
    {
        "id": 1,
        # Last article: May 9, 2023 (NVIDIA Q1 earnings)
        # Investment window: 1 month after last article
        "period_start": "2023-05-10",
        "period_end": "2023-06-12",  # +1 day to include Jun 9 (trading day)
        "tickers": ["NVDA", "MSFT", "GOOGL", "INTC", "SNAP", "IBM", "SPY", "AMD", "MRNA", "DIS"],
    },
    {
        "id": 2,
        # Last article: March 17, 2023 (First Republic scrambles)
        # Investment window: 1 month after last article
        "period_start": "2023-03-20",
        "period_end": "2023-04-21",
        "tickers": ["JPM", "SCHW", "KRE", "GLD", "AAPL", "PFE", "SPY", "WFC", "VNO", "COIN"],
    },
    {
        "id": 3,
        # Last article: April 28, 2022 (META Q1 earnings)
        # Investment window: 1 month after last article
        "period_start": "2022-05-02",
        "period_end": "2022-06-03",
        "tickers": ["XOM", "META", "COST", "DVN", "AMZN", "LMT", "SPY", "WMT", "TGT", "TSLA"],
    },
]

OUTPUT_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "frontend",
    "src",
    "data",
    "stockPrices.js",
)


def fetch_round_data(round_config):
    """Fetch daily closing prices for all tickers in a round."""
    result = {"tickers": {}, "returns": {}}

    for ticker in round_config["tickers"]:
        print(f"  Fetching {ticker}...")
        stock = yf.Ticker(ticker)
        hist = stock.history(
            start=round_config["period_start"],
            end=round_config["period_end"],
            interval="1d",
        )

        if hist.empty:
            print(f"    WARNING: No data for {ticker}")
            continue

        prices = []
        for date, row in hist.iterrows():
            prices.append({
                "date": date.strftime("%Y-%m-%d"),
                "close": round(row["Close"], 2),
            })

        if len(prices) >= 2:
            first = prices[0]["close"]
            last = prices[-1]["close"]
            ret = round(((last - first) / first) * 100, 1)
            result["returns"][ticker] = ret

        result["tickers"][ticker] = prices

    # Determine actual trading day range
    all_dates = set()
    for ticker_prices in result["tickers"].values():
        for p in ticker_prices:
            all_dates.add(p["date"])

    sorted_dates = sorted(all_dates)
    result["period_start"] = sorted_dates[0] if sorted_dates else round_config["period_start"]
    result["period_end"] = sorted_dates[-1] if sorted_dates else round_config["period_end"]

    return result


def write_stock_prices_js(all_rounds, output_path):
    """Write the stockPrices.js ES module file."""
    lines = [
        "// Auto-generated by scripts/fetch_stock_data.py — do not edit manually",
        "// Run: python scripts/fetch_stock_data.py",
        "",
        "export const stockPrices = {",
    ]

    for round_id, data in sorted(all_rounds.items()):
        lines.append(f"  {round_id}: {{")
        lines.append(f'    period_start: "{data["period_start"]}",')
        lines.append(f'    period_end: "{data["period_end"]}",')
        lines.append(f"    tickers: {{")

        for ticker, prices in data["tickers"].items():
            prices_json = json.dumps(prices)
            lines.append(f"      {ticker}: {prices_json},")

        lines.append(f"    }},")
        lines.append(f"  }},")

    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"\nWritten to {output_path}")


def main():
    all_rounds = {}

    for rc in ROUNDS:
        print(f"\n=== Round {rc['id']} ({rc['period_start']} to {rc['period_end']}) ===")
        data = fetch_round_data(rc)
        all_rounds[rc["id"]] = data

        print(f"\n  Actual returns for Round {rc['id']}:")
        for ticker, ret in data["returns"].items():
            sign = "+" if ret >= 0 else ""
            print(f"    {ticker}: {sign}{ret}%")

    write_stock_prices_js(all_rounds, os.path.abspath(OUTPUT_PATH))

    # Print gameData.js update summary
    print("\n" + "=" * 60)
    print("UPDATE gameData.js with these real returns:")
    print("=" * 60)
    for rc in ROUNDS:
        data = all_rounds[rc["id"]]
        print(f"\nRound {rc['id']}:")
        print(f"  period_start: \"{data['period_start']}\"")
        print(f"  period_end: \"{data['period_end']}\"")
        for ticker, ret in data["returns"].items():
            print(f"  {ticker}: {ret}")


if __name__ == "__main__":
    main()
